### ISSUE TITLE
Integration with Dialogflow

### ISSUE THREAD

**Issue by msolefonte** [jolzee/chat-teneo-vue#3]
I would like to be able to use the template to deploy a Dialogflow bot, but I am not used at all to Vue.js and there is no enough documentation. Is there a way I can send requests to Dialogflow instead of Teneo?

**Comment by jolzee** [comment]
Hi Marc - Leopard is specifically built to talk to Teneo in that it calls Teneo endpoints and then parses its JSON responses. Now that's not to say it couldn't work for DialogFlow. It would  just require some development effort to switch out the API calls to Teneo with ones to DialogFlow.  

Look in the actions section of store.js for the areas where requests are made out to Teneo - specifically "login", "sendUserInput" and "logout" and work out from there. Currently all Teneo requests start with "Vue.jsonp(....."

If that's too much of task then you might want to check out [Teneo Developers](https://www.teneo.ai/) . Try sign up and you will get a developer sandbox for Teneo.

**Comment by msolefonte** [comment]
I have taken a look to the Vue.jsonp() calls and now it seems much more clearer. I think I can redo that to directly call to DialogFlow. If I am able to do it, would you like me to send a PR? Of course, I would try to keep it as optional as possible (config option, for example), without interfering with the Teneo common use.

**Comment by jolzee** [comment]
Absolutely welcomed - If you get a working version it would be great to have a PR to the following branch https://github.com/jolzee/chat-teneo-vue/tree/dialogflow .

**Comment by msolefonte** [comment]
I have been working and have find a functional solution, but code is too much hardcoded to work with Teneo and it is hard to have a compatible solution for both options. I am going to try it but it seems to require a lot of job.

**Comment by jolzee** [comment]
Agreed having both CAI platforms in a single codebase might be a bit overkill in that they function slightly differently in their capabilities.  A fork or branch might be the way to go.

**Comment by msolefonte** [comment]
I thought you wanted it in a branch but with the objective of merging it. It is clear now.
