### ISSUE TITLE
How to disable the side menu?

### ISSUE THREAD

**Issue by msolefonte** [jolzee/chat-teneo-vue#6]
I think that it would be interesting to have the possibility of replacing the menu button in the chat with a down arrow that closes the chat directly. In my opinion, this way it is more compact and cleaner. However, I do not find where it is declared. 

I found the side menu in `App.vue`, but what I want do disable is the button.

**Comment by jolzee** [comment]
The button is handled in `App.vue`.  Search for `toggleEmbedButton` and `showChatButton`.

**Comment by jolzee** [comment]
Sorry misunderstood.   The menu is controlled by an app drawer and triggered in `App.vue`. Specifically:

```
<v-toolbar-side-icon
            @click.stop="drawer = !drawer"
            style="flex: 0 0 auto;"
            :color="toolbarColor"
          ></v-toolbar-side-icon>
```

**Comment by msolefonte** [comment]
Thank you, it just worked.
